### PR TITLE
Changed layout from single page to pages

### PR DESCRIPTION
**Pull request by digen**
Changed layout from single page website to multiple pages. The structure is similar to inpycon2014 website. The reason for doing is was to have a separate speakers.html page.

### CODE REVIEW

**Comment by sanketsaurav** [comment]
I'm not sure that's a good idea. Separate speaker page makes sense, only because it has content that's not critical to show on the home page. We can have a separate page for selected talks. But other sections like schedule, sponsors, etc. should be there on the landing page itself. Having separate pages does not make sense, since the content remains the same.

**Comment by sanketsaurav** [comment]
Fixed with [d218e](https://github.com/pythonindia/pybelgaum2015/commit/d218e850f140518b5bb23e3c7ada356fedb68307).

**Comment by kracekumar** [comment]
Deployed

**Comment by sanketsaurav** [comment]
@kracekumar `speakers.html` seems to be missing in prod. Can you check once? The link gives a 404.

**Comment by kracekumar** [comment]
Oh, we redirect pybelgaum.org to pybelgaum.org/2015., the right url is
http://pybelgaum.org/2015/speakers.html

On Thu, Feb 19, 2015 at 12:31 PM, Sanket Saurav notifications@github.com
wrote:

> @kracekumar https://github.com/kracekumar speakers.html seems to be
> missing in prod. Can you check once? The link gives a 404.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/pybelgaum2015/pull/2#issuecomment-75007107
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sanketsaurav** [comment]
@kracekumar The redirect isn't being handled on Jekyll level, is it?

**Comment by kracekumar** [comment]
It should be a href="speakers.html" not a href="/speakers.html". nginx is
redirecting.

On Thu, Feb 19, 2015 at 1:03 PM, Sanket Saurav notifications@github.com
wrote:

> @kracekumar https://github.com/kracekumar The redirect isn't being
> handled on Jekyll level, is it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/pybelgaum2015/pull/2#issuecomment-75009459
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sanketsaurav** [comment]
Doing that will break it in dev. Can we handle redirection at Jekyll level? We can have the base URL in the Jekyll context, and use that in the templates. Would be cleaner IMO.

**Comment by kracekumar** [comment]
I modified this in index.html and it worked, is there any other place I
need to look ? If you can find a way with jekyll, please go ahead and push
the changes.

On Thu, Feb 19, 2015 at 1:15 PM, Sanket Saurav notifications@github.com
wrote:

> Doing that will break it in dev. Can we handle redirection at Jekyll
> level? We can have the base URL in the Jekyll context, and use that in the
> templates. Would be cleaner IMO.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonindia/pybelgaum2015/pull/2#issuecomment-75010428
> .

## 

Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by sanketsaurav** [comment]
~~Will do. I'll push the fix later this evening.~~

Fixed with [66136](https://github.com/pythonindia/pybelgaum2015/commit/66136141229a1474cb3fe4964bdfed9db232abb3). Please deploy.

**Pull request merged**
